version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      gha:
        update-types: [ "major", "minor", "patch" ]
    schedule:
      interval: "weekly"
    labels:
      - github-actions-update
  - package-ecosystem: docker
    directory: "/apache2"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - docker-base-update
  - package-ecosystem: docker
    directory: "/apache2-shibboleth"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - docker-base-update
  - package-ecosystem: docker
    directory: "/haproxy28"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - docker-base-update
  - package-ecosystem: docker
    directory: "/php72-apache2"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - docker-base-update
  - package-ecosystem: docker
    directory: "/php72-apache2-node14-composer2"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - docker-base-update
  - package-ecosystem: docker
    directory: "/php72-apache2-node16-composer2"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - docker-base-update
  - package-ecosystem: docker
    directory: "/php82-apache2"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - docker-base-update
  - package-ecosystem: docker
    directory: "/php82-apache2-node20-composer2"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - docker-base-update
  - package-ecosystem: docker
    directory: "/php85-apache2"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - docker-base-update
  - package-ecosystem: docker
    directory: "/php85-apache2-node24"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - docker-base-update
  - package-ecosystem: docker
    directory: "/python3"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - docker-base-update
  - package-ecosystem: docker
    directory: "/satosa"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - docker-base-update
