---
name: Build the Apache2 and Shibboleth container

on:
  push:
    branches:
      - main
    paths:
      - "apache2-shibboleth/**"
      - ".github/workflows/build-apache2-shibboleth.yaml"
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:


jobs:
  build-push-apache2-shibboleth:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./apache2-shibboleth
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/openconext/openconext-basecontainers/apache2-shibboleth:latest
            ghcr.io/openconext/openconext-basecontainers/apache2-shibboleth:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha
