name: Build the Haproxy container

on:
  push:
    branches:
      - "main"
      - "feature/haproxy-26"
  schedule:
    - cron: '30 7 * * *'

jobs:
  build-push-php80:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add the https key to the haproxy certificate file
        run: |
          echo "${{ secrets.LOADBALANCER_HTTP_KEY }}" > ./haproxy26/conf/haproxy.pem

      - name: Add the https certificate to the haproxy certificate file
        run: |
          cat ./haproxy26/conf/haproxy.crt >> ./haproxy26/conf/haproxy.pem

      - name: Chmod the haproxy.pem
        run: |
          chmod 444 ./haproxy26/conf/haproxy.pem

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./haproxy26
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/openconext/openconext-basecontainers/haproxy26:latest
            ghcr.io/openconext/openconext-basecontainers/haproxy26:${{ github.sha }}
