name: Build the Haproxy container

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    
  schedule:
    - cron: '30 7 * * *'

jobs:
  build-push-haproxy28:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add the https key to the haproxy certificate file
        run: |
          echo "${{ secrets.LOADBALANCER_HTTP_KEY }}" > ./haproxy28/conf/haproxy.pem

      - name: Add the https certificate to the haproxy certificate file
        run: |
          cat ./haproxy28/conf/haproxy.crt >> ./haproxy28/conf/haproxy.pem

      - name: Chmod the haproxy.pem
        run: |
          chmod 444 ./haproxy28/conf/haproxy.pem

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./haproxy28
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/openconext/openconext-basecontainers/haproxy28:latest
            ghcr.io/openconext/openconext-basecontainers/haproxy28:${{ github.sha }}
