name: Build the PHP 8.0 FPM Apache2 container

on:
  push:
    branches:
      - "main"
    paths:
      - "php80-fpm-apache2"
  schedule:
    - cron: '30 7 * * *'

jobs:
  build-push-php80:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./php80-fpm-apache2
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/openconext/openconext-basecontainers/php80-fpm-apache2:latest
            ghcr.io/openconext/openconext-basecontainers/php80-fpm-apache2:${{ github.sha }}
