---
name: Build the PHP 8.2 Apache2 container

on:
  push:
    paths:
      - "php82-apache2/**"
      - ".github/workflows/build-php82-apache2.yaml"
  schedule:
    - cron: '30 7 * * *'
  workflow_dispatch:

jobs:
  build-push-php82:
    runs-on: "ubuntu-22.04"
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "linux/amd64,linux/arm64"
          # The latest version will lead to segmentation fault.
          image: "tonistiigi/binfmt:qemu-v7.0.0-28"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./php82-apache2
          platforms: "linux/arm64"
          # only push the latest tag on the main branch
          push: "${{ github.ref == 'refs/heads/main' }}"
          tags: |
            ghcr.io/openconext/openconext-basecontainers/php82-apache2:latest
            ghcr.io/openconext/openconext-basecontainers/php82-apache2:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha

      # Setup tmate session
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: failure()
