name: Delete old container images

on:
  schedule:
    - cron: '40 12 * * *'

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the latest 7 versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'openconext-basecontainers/php*'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 7
          delete-only-untagged-versions: 'false'
          ignore-versions: '/latest/g'
