name: Delete old container images

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  clean-php72-fpm-apache2:
    name: Delete old unused container images from php72-fpm-apache2
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the latest 7 versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'openconext-basecontainers/php72-fpm-apache2'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 7
          delete-only-untagged-versions: 'false'
          ignore-versions: '/latest/g'
  clean-php82-fpm-apache2:
    name: Delete old unused container images from php82-fpm-apache2
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the latest 7 versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'openconext-basecontainers/php82-fpm-apache2'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 7
          delete-only-untagged-versions: 'false'
          ignore-versions: '/latest/g'
  clean-php82-apache2:
    name: Delete old unused container images from php82-apache2
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the latest 7 versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'openconext-basecontainers/php82-apache2'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 7
          delete-only-untagged-versions: 'false'
          ignore-versions: '/latest/g'
  clean-php72-apache2-node14-composer2:
    name: Delete old unused container images from php72-apache2-node14-composer2
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the latest 7 versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'openconext-basecontainers/php72-apache2-node14-composer2'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 7
          delete-only-untagged-versions: 'false'
          ignore-versions: '/latest/g'
  clean-php82-apache2-node14-composer2:
    name: Delete old unused container images from php82-apache2-node14-composer2
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the latest 7 versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'openconext-basecontainers/php82-apache2-node14-composer2'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 7
          delete-only-untagged-versions: 'false'
          ignore-versions: '/latest/g'
  clean-php72-apache2-node16-composer2:
    name: Delete old unused container images from php72-apache2-node16-composer2
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the latest 7 versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'openconext-basecontainers/php72-apache2-node16-composer2'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 7
          delete-only-untagged-versions: 'false'
          ignore-versions: '/latest/g'
  clean-php82-apache2-node16-composer2:
    name: Delete old unused container images from php82-apache2-node16-composer2
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the latest 7 versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'openconext-basecontainers/php82-apache2-node16-composer2'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 7
          delete-only-untagged-versions: 'false'
          ignore-versions: '/latest/g'
  clean-php80-apache2-node14-composer2:
    name: Delete old unused container images from php80-apache2-node14-composer2
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the latest 7 versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'openconext-basecontainers/php80-apache2-node14-composer2'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 7
          delete-only-untagged-versions: 'false'
          ignore-versions: '/latest/g'
  clean-php80-apache2:
    name: Delete old unused container images from php80-apache2
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the latest 7 versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'openconext-basecontainers/php80-apache2'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 7
          delete-only-untagged-versions: 'false'
          ignore-versions: '/latest/g'
  clean-php80-fpm-apache2:
    name: Delete old unused container images from php80-fpm-apache2
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the latest 7 versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'openconext-basecontainers/php80-fpm-apache2'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 7
          delete-only-untagged-versions: 'false'
          ignore-versions: '/latest/g'
  clean-php72-apache2:
    name: Delete old unused container images from php72-apache2
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the latest 7 versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'openconext-basecontainers/php72-apache2'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 7
          delete-only-untagged-versions: 'false'
          ignore-versions: '/latest/g'
  clean-haproxy26:
    name: Delete old unused container images from haproxy26
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the latest 7 versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'openconext-basecontainers/haproxy26'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 7
          delete-only-untagged-versions: 'false'
          ignore-versions: '/latest/g'
  clean-apache2:
    name: Delete old unused container images from Apache2
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the latest 7 versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'openconext-basecontainers/apache2'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 7
          delete-only-untagged-versions: 'false'
          ignore-versions: '/latest/g'
  clean-apache2-shibboleth:
    name: Delete old unused container images from Apache2 Shibboleth
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the latest 7 versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'openconext-basecontainers/apache2-shibboleth'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 7
          delete-only-untagged-versions: 'false'
          ignore-versions: '/latest/g'
